### ISSUE TITLE
zip_sva_perf run hw file decompress failed

### ISSUE THREAD

**Issue by youngersh** [Linaro/uadk#298]
prepare:
dd if=/dev/urandom of=origin bs=1K count=512
zip_sva_perf --in origin --dest

test:
zip_sva_perf -d --in dest --out origin2

result:
Missing IN list file!
Fail to run hw_ifl_perf() (-22)!

I think the error is caused by the 'load_ilist'. But I can't understand the use of 'ilist'. So I need you help.
@hzhuang1

**Comment by hzhuang1** [comment]
For your reference, you could print out command in sanity_test.sh.

Let's come back your issue. You're trying to compress data in BLOCK mode with multiple BLOCKS, and decompress data in BLOCK mode, too. So you need to generate gzip_list.bin in compression.
$zip_sva_perf --in origin --out dest --olist /tmp/gzip_list.bin -b 1024
$zip_sva_perf -d --in dest --out origin2 --inlist /tmp/gzip_list.bin -b 1024

gzip_list.bin records each block size.
