### ISSUE TITLE
block mode fail in multiple blocks cases

### ISSUE THREAD

**Issue by hzhuang1** [Linaro/uadk#3]
When test multiple blocks in block mode, case in "example.c" fails. It could be observed in both "master" and "hzhuang1-sva-3.3" branch.

**Comment by hzhuang1** [comment]
"avail_in" is also used in block mode. Refer to #2  issue. Try to port the patch from stream mode in "hzhuang1-sva-3.3" branch.

**Comment by haofang111** [comment]
Just review the test_rand_buff(ZLIB, 0) block mode test, but it is looks like stream, three blocks throw to HW one by one, but every block is independent, three blocks can not combine a whole file.

**Comment by hzhuang1** [comment]
> Just review the test_rand_buff(ZLIB, 0) block mode test, but it is looks like stream, three blocks throw to HW one by one, but every block is independent, three blocks can not combine a whole file.

So what's the usage of block mode? How do we make use of it in real scenario?

**Comment by hzhuang1** [comment]
It's unnecessary to split one block transfer into multiple small ones. So close it.
