### ISSUE TITLE
Potential error(e.g. deadlock, ill performance) due to the unreleased lock

### ISSUE THREAD

**Issue by anson-lo** [Linaro/uadk#343]
Dear developers:
Thank you for your checking. In the method` test_sec_cipher_async`, the lock `&test_sec_mutex` maybe not be released correctly when the control flow goes to the `else if` branch and go to `out`, bypassing the unreleased lock.
https://github.com/Linaro/uadk/blob/41313cde5977b4316cb3403175b68f2e8d13f1f9/test/hisi_sec_test/test_hisi_sec.c#L1055
https://github.com/Linaro/uadk/blob/41313cde5977b4316cb3403175b68f2e8d13f1f9/test/hisi_sec_test/test_hisi_sec.c#L1064

```
static int test_sec_cipher_async(void *arg)
{
	...;
	pthread_mutex_lock(&test_sec_mutex);
	...;
	do {
try_do_again:
		ret = wd_do_cipher_async(h_sess, req);
		if (ret == -EBUSY) { // busy
			usleep(100);
			goto try_do_again;
		} else if (ret) {
			SEC_TST_PRT("test sec cipher send req is error!\n");
			goto out;   // bypass the unlock, leading to unreleased lock
		}
		cnt--;
	} while (cnt);
	pthread_mutex_unlock(&test_sec_mutex);
	...;
out:
	if (h_sess)
		wd_cipher_free_sess(h_sess);

	return ret;
}
```

Best,

**Comment by hzhuang1** [comment]
@Liulongfang Longfang, could you help to check this? Thanks

**Comment by anson-lo** [comment]
Hi, developers @Liulongfang 

Any comments would be highly appreciated. Thank you.

Best Regards,

**Comment by hzhuang1** [comment]
Fixed in https://github.com/Linaro/uadk/pull/350

**Comment by anson-lo** [comment]
@hzhuang1 Thank you!
