### ISSUE TITLE
UADK multi-queue scheduling problem

### ISSUE THREAD

**Issue by Liulongfang** [Linaro/uadk#359]
UADK's scheduling for multiple queues will decrease performance after more than 16 queues.

In synchronous mode, 4threads，16 queues
algname: length: perf: iops: CPU_rate:
aes-128-cbc 1024Bytes 1026159.6KB/s 1002.0Kops 398.80%

In synchronous mode, 4threads， 24 queues
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       1001670.6KB/s   978.0Kops       398.60%

In synchronous mode, 4threads， 32 queues
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       821041.8KB/s    801.6Kops       386.40%

**Comment by Liulongfang** [comment]
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       1026159.6KB/s   1002.0Kops      398.80%

**Comment by hzhuang1** [comment]
Do these tests in a test branch (https://github.com/hzhuang1/uadk/tree/debug_sec_v0.1). In this test branch, there's a patch to dump the duty cycles in different periods in each transmission.

```
commit 582608f0b62e802eb3aab672f0e69bfc432e7de3
Author: Haojian Zhuang <haojian.zhuang@linaro.org>
Date:   Fri Sep 10 14:24:44 2021 +0800

    debug: check the duty cycle
    
    Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>
```
With this patch, it could dump four periods. They're pick next ctx, lock in algorithm, cipher send, cipher recv.

And there's another patch to remove the mutex in UADK scheduler.

```
commit e87ce6d78d6fb24a7cb85221c9b0c3038c9e0374 (HEAD -> debug_sec_v0.1, hzhuang1/debug_sec_v0.1)
Author: Haojian Zhuang <haojian.zhuang@linaro.org>
Date:   Sun Sep 12 08:04:38 2021 +0800

    sched: remove the lock
    
    Use lock-free to select one ctx from region.
    
    Atomic operations are used to make sure each operation on region->last
    variable is atomic. Since other global variables are treated as contant
    value. And updating local variables won't change variables in other
    threads.
    
    Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>
```

hzhuang1@ubuntu:~/uadk$ ./zip_run.sh 
start UADK benchmark test.
    [--algname]: aes-128-cbc
    [--mode]:    1
    [--optype]:  0
    [--syncmode]:0
    [--pktlen]:  1024
    [--seconds]: 3
    [--thread]:  4
    [--multi]:   1
    [--ctxnum]:  16
    [--algclass]:cipher
    [--acctype]: 0
    [--engine]:  
hisi sec init Kunpeng920!
algname:	length:		perf:		iops:		CPU_rate:
aes-128-cbc	1024Bytes	853373.8KB/s	833.3Kops 	399.64%
duty cycle:9.08%, 6.46%, 15.58%, 66.27%
start UADK benchmark test.
    [--algname]: aes-128-cbc
    [--mode]:    1
    [--optype]:  0
    [--syncmode]:0
    [--pktlen]:  1024
    [--seconds]: 3
    [--thread]:  4
    [--multi]:   1
    [--ctxnum]:  24
    [--algclass]:cipher
    [--acctype]: 0
    [--engine]:  
hisi sec init Kunpeng920!
algname:	length:		perf:		iops:		CPU_rate:
aes-128-cbc	1024Bytes	856045.1KB/s	835.9Kops 	399.62%
duty cycle:9.43%, 6.16%, 16.18%, 66.99%
start UADK benchmark test.
    [--algname]: aes-128-cbc
    [--mode]:    1
    [--optype]:  0
    [--syncmode]:0
    [--pktlen]:  1024
    [--seconds]: 3
    [--thread]:  4
    [--multi]:   1
    [--ctxnum]:  32
    [--algclass]:cipher
    [--acctype]: 0
    [--engine]:  
hisi sec init Kunpeng920!
algname:	length:		perf:		iops:		CPU_rate:
aes-128-cbc	1024Bytes	856809.9KB/s	836.6Kops 	399.64%
duty cycle:8.59%, 6.76%, 15.51%, 66.39%

With the new data, we could observe all data are similar while ctx numbers are changed. CTX numbers should be always great than thread numbers.

**Comment by Liulongfang** [comment]
OK
