### ISSUE TITLE
UADK multi-threaded performance issues

### ISSUE THREAD

**Issue by Liulongfang** [Linaro/uadk#360]
UADK multi-threaded performance cannot be increased to the hardware speed limit
8 threads：
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       1254809.0KB/s   1225.2Kops      785.40%

16 threads：
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       1420551.0KB/s   1387.2Kops      1564.60%

32 threads：
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       539262.2KB/s    526.6Kops       3138.20%

In contrast, in the same synchronization mode, warpdrive can reach the hardware speed limit by adding threads:
8 threads：
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       2970516.8KB/s   2900.8Kops      799.20%

16 threads：
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       5664155.0KB/s   5531.4Kops      1597.80%

32 threads：
algname:        length:         perf:           iops:           CPU_rate:
aes-128-cbc     1024Bytes       8293766.6KB/s   8099.2Kops      3194.80%

**Comment by hzhuang1** [comment]
With the debug branch (https://github.com/hzhuang1/uadk/tree/debug_sec_v0.1), the performance data is in below.

start UADK benchmark test.
    [--algname]: aes-128-cbc
    [--mode]:    1
    [--optype]:  0
    [--syncmode]:0
    [--pktlen]:  1024
    [--seconds]: 3
    [--thread]:  8
    [--multi]:   1
    [--ctxnum]:  16
    [--algclass]:cipher
    [--acctype]: 0
    [--engine]:  
hisi sec init Kunpeng920!
algname:	length:		perf:		iops:		CPU_rate:
aes-128-cbc	1024Bytes	1569103.4KB/s	1532.1Kops 	799.21%
duty cycle:10.96%, 7.26%, 13.15%, 66.76%
start UADK benchmark test.
    [--algname]: aes-128-cbc
    [--mode]:    1
    [--optype]:  0
    [--syncmode]:0
    [--pktlen]:  1024
    [--seconds]: 3
    [--thread]:  16
    [--multi]:   1
    [--ctxnum]:  32
    [--algclass]:cipher
    [--acctype]: 0
    [--engine]:  
hisi sec init Kunpeng920!
algname:	length:		perf:		iops:		CPU_rate:
aes-128-cbc	1024Bytes	2627257.0KB/s	2565.5Kops 	1598.67%
duty cycle:11.45%, 7.16%, 12.44%, 66.90%
start UADK benchmark test.
    [--algname]: aes-128-cbc
    [--mode]:    1
    [--optype]:  0
    [--syncmode]:0
    [--pktlen]:  1024
    [--seconds]: 3
    [--thread]:  32
    [--multi]:   1
    [--ctxnum]:  64
    [--algclass]:cipher
    [--acctype]: 0
    [--engine]:  
hisi sec init Kunpeng920!
algname:	length:		perf:		iops:		CPU_rate:
aes-128-cbc	1024Bytes	2491805.3KB/s	2433.1Kops 	3198.24%
duty cycle:38.54%, 5.42%, 7.29%, 47.92%

All three kinds of performance data are increased. There're two reasons at here.

1. With the commit to remove lock in UADK scheduler.
```
commit e87ce6d78d6fb24a7cb85221c9b0c3038c9e0374 (HEAD -> debug_sec_v0.1, hzhuang1/debug_sec_v0.1)
Author: Haojian Zhuang <haojian.zhuang@linaro.org>
Date:   Sun Sep 12 08:04:38 2021 +0800

    sched: remove the lock
    
    Use lock-free to select one ctx from region.
    
    Atomic operations are used to make sure each operation on region->last
    variable is atomic. Since other global variables are treated as contant
    value. And updating local variables won't change variables in other
    threads.
    
    Signed-off-by: Haojian Zhuang <haojian.zhuang@linaro.org>
```

2. Keep CTX numbers always greater than thread numbers.

| Threads Number | CTX Number |
| :-- | :-- |
| 8 | 16 |
| 16 | 32 |
| 32 | 64 |

**Comment by Liulongfang** [comment]
OK
