### ISSUE TITLE
conf.sh --static fails to build

### ISSUE THREAD

**Issue by fboudra** [Linaro/uadk#90]
/bin/bash ../../libtool  --tag=CC   --mode=link aarch64-linux-gnu-gcc -Wall -fno-strict-aliasing -I../../include -pthread -g -O2 -Wl,-rpath,'/usr/local/lib'  -o test_hisi_hpre test_hisi_hpre.o ../../.libs/libwd.a ../../.libs/libwd_crypto.a ../../.libs/libhisi_hpre.a -ldl 
libtool: link: aarch64-linux-gnu-gcc -Wall -fno-strict-aliasing -I../../include -pthread -g -O2 -Wl,-rpath -Wl,/usr/local/lib -o test_hisi_hpre test_hisi_hpre.o  ../../.libs/libwd.a ../../.libs/libwd_crypto.a ../../.libs/libhisi_hpre.a -ldl -pthread
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_sign_out_transfer':
/home/buildslave/uadk/drv/hisi_hpre.c:1225: undefined reference to `wd_sm2_get_sign_out_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `sm2_enc_out_transfer':
/home/buildslave/uadk/drv/hisi_hpre.c:1279: undefined reference to `wd_sm2_get_enc_out_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `sm2_kg_out_transfer':
/home/buildslave/uadk/drv/hisi_hpre.c:1259: undefined reference to `wd_sm2_get_kg_out_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_prepare_pubkey':
/home/buildslave/uadk/drv/hisi_hpre.c:847: undefined reference to `wd_ecc_get_pubkey_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_prepare_prikey':
/home/buildslave/uadk/drv/hisi_hpre.c:784: undefined reference to `wd_ecc_get_prikey_params'
/usr/bin/ld: ../../.libs/libhisi_hpre.a(hisi_hpre.o): in function `ecc_prepare_sign_in':
/home/buildslave/uadk/drv/hisi_hpre.c:970: undefined reference to `wd_ecc_get_prikey_params'
collect2: error: ld returned 1 exit status
make[3]: *** [Makefile:395: test_hisi_hpre] Error 1
make[3]: Leaving directory '/home/buildslave/uadk/test/hisi_hpre_test'
make[2]: *** [Makefile:352: all-recursive] Error 1
make[2]: Leaving directory '/home/buildslave/uadk/test'
make[1]: *** [Makefile:722: all-recursive] Error 1
make[1]: Leaving directory '/home/buildslave/uadk'
make: *** [Makefile:516: all] Error 2

**Comment by fboudra** [comment]
https://github.com/Linaro/uadk/pull/92

**Comment by hzhuang1** [comment]
Since it's fixed in #92 , close it now.
